[project]
name = "task_agent"
version = "0.0.1"
description = "An agent that can chat with project members."
authors = [
    { name = "Thothy", email = "ai.thothy@gmail.com" },
]
license = { text = "Apache-2.0" }
requires-python = ">=3.12"
dependencies = [
    "langgraph>=0.4.7",
    "langgraph-checkpoint>=2.0.26",
    "langgraph-sdk>=0.1.67",
    "langchain>=0.3.25",
    "langchain-core>=0.3.63",
    "langchain-openai>=0.3.18",
    "langchain-anthropic>=0.3.14",
    "langmem>=0.0.26",
    "psycopg[binary,pool]>=3.2.9",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
    "blog_agent",
    "chat_agent",
    "news_agent",
    "thothy-backend-libs",
]

[project.optional-dependencies]
dev = ["mypy>=1.11.1", "ruff>=0.4.8", "pytest-asyncio>=0.23.7"]

[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["task_graph", "thothy.task_graph"]
[tool.setuptools.package-dir]
"task_graph" = "src/task_graph"
"thothy.task_graph" = "src/task_graph"


[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.ruff]
lint.select = [
    "E",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "D",    # pydocstyle
    "D401", # First line should be in imperative mood
    "T201",
    "UP",
]
lint.ignore = ["UP006", "UP007", "UP035", "D417", "E501"]
include = ["*.py", "*.pyi", "*.ipynb"]
[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
ignore_errors = true 